Create documentation for larammerce CRUD.
larammerce/larammerce-docs pull request #42
Opened 2023-02-23 08:28 UTC by ShammasAmir

Hi. I have created a new documentation for larammerce CRUD.

2023-02-23 08:46 UTC, arash-khajelou requested changes

2023-02-23 08:46 UTC, arash-khajelou commented on 8.x/core-concepts/cruds.md
> +Run the following command in the CMD:
Let’s say terminal or command line instead of CMD because cmd is just a command shell related to windows.

2023-02-23 08:46 UTC, arash-khajelou commented on 8.x/core-concepts/cruds.md
> +![](/40.png)
Try to write alt notes for your photos.

2023-02-23 08:46 UTC, arash-khajelou commented on 8.x/core-concepts/cruds.md
> +```stylus{8-10}
This file’s format is .scss, not .stylus

2023-02-24 22:07 UTC, ShammasAmir commented
Hi sir.I made your requested corrections into "cruds.md" file.

2023-03-01 03:50 UTC, ShammasAmir commented
Hi. I added fullscreen property to video source.

TG-907 #pr-created

2023-03-03 11:16 UTC, ShammasAmir commented
Hi. I added the annotations link to the crud document.

TG-907 #pr-created

2023-03-26 13:46 UTC, reyhane-rangamiz commented on 8.x/core-concepts/cruds.md
>              "lastPage" => $todos->lastPage(),
Missing
"count" => $todos->perPage(),  
This command should also get changed.
40:19'

2023-04-05 05:58 UTC, closed without merging