Reyhane 912
larammerce/larammerce-docs pull request #47
Opened 2023-03-15 07:50 UTC by reyhane-rangamiz

a comprehensive article for both development and production environment setup has been composed.

2023-03-30 09:17 UTC, ShammasAmir requested changes
Hi. Some minor changes are requested.

2023-03-30 21:21 UTC, reyhane-rangamiz commented on 8.x/getting-started/installation.md
> +1. Create a file on `/larammerce-base-theme/public/views/$`.
@ShammasAmir 
Thank you for the attention. it was a writing mistake. completely solved.

2023-04-06 08:26 UTC, ShammasAmir requested changes
@reyhane-rangamiz : Hi. One minor change proposed.

2023-04-06 08:26 UTC, ShammasAmir commented on 8.x/getting-started/installation.md
> +direnv allow
Add "space" and "dot" -> direnv allow .

2023-04-12 20:07 UTC, ShammasAmir requested changes
Hi. The document is great. Some changes have been suggested.

2023-04-12 20:08 UTC, ShammasAmir requested changes
Hi. The document is great. Some changes have been suggested.

2023-04-13 01:40 UTC, ShammasAmir requested changes
Some other changes have been proposed.

2023-04-13 01:40 UTC, ShammasAmir commented on 8.x/getting-started/installation.md
> +
In the browser, type "http://0.0.0.0:8080/admin" to see the login page.
In the terminal, go to the `~/projects/larammerce/database/seeders/` directory and run:
```bash
vim UsersTableSeeder.php
```
In this file, you can see the username and password for admin user. Insert these values into the login fields to enter the admin panel.

2023-04-13 01:40 UTC, ShammasAmir commented on 8.x/getting-started/installation.md
> +Once you logged in as admin on `localhost:8080/admin`, press plus button on the left buttom of the page ,create a folder and equalized some random values in the form displayed.
`localhost:8080/admin` -> `http://0.0.0.0:8080/admin`
equalized -> enter

2023-04-13 01:40 UTC, ShammasAmir commented on 8.x/getting-started/installation.md
> +3.Now deploy the project on `~ /larammerce-base-theme` directory:
`~ /larammerce-base-theme` -> `larammerce-base-theme`

2023-04-13 01:40 UTC, ShammasAmir commented on 8.x/getting-started/installation.md
> +Finally, press `edit web page` button in the form, select the url name you created, and save.(here the url name is test)<br>
select the url name -> select the blade file name

here the url name is test -> Here the blade file name is `test`

2023-04-13 01:40 UTC, ShammasAmir commented on 8.x/getting-started/installation.md
> +Afterward, another form will be displayed. Here you may need to build a theme file prior to editing the web page.
build a theme file -> build a blade file

2023-04-13 01:40 UTC, ShammasAmir commented on 8.x/getting-started/installation.md
> +See the result on `localhost:8080/test`.
`localhost:8080/test` -> ` http://0.0.0.0:8080/test`

2023-04-14 11:35 UTC, merged